### ISSUE TITLE
Crashes after installing

### ISSUE THREAD

**Issue by CrabbieMike** [solsticegamestudios/GModCEFCodecFix#101]
After installing CEFCCodecFix the game crashes immediately after launching

1. Windows 11
2. Garyys mod 64 bit beta running the 64 bit build

Uploading 8mb.video-iuX-nhCGAozg.mp4…

**Comment by CrabbieMike** [comment]
Looks like video didnt upload on github so i uploaded it as an unlisted youtube video

https://youtu.be/f3QJ4BryASY

**Comment by WinterPhoenix** [comment]
Try launching from Steam. If it still crashes, delete the chromium.log file in your GMod install, run GMod again, let it crash, then post your chromium.log file here

**Comment by CrabbieMike** [comment]
Here is the entire contents of chromium.log after following those steps

[0303/003344.805:WARNING:resource_util.cc(94)] Please customize CefSettings.root_cache_path for your application. Use of the default value may lead to unintended process singleton behavior.
[0303/003344.816:ERROR:main_runner.cc(251)] ContentMainRun failed with exit code 21

**Comment by WinterPhoenix** [comment]
okay. obvious troubleshooting steps first:
1. Do Steam > Garry's Mod > Properties > Installed Files > Verify integrity
2. Wait for Steam to finish "updating" GMod
3. Run GModCEFCodecFix again
4. If GMod still crashes, go to `garrysmod/crashes/` and email the most recent .DMP and .TXT files my email at winter@solsticegamestudios.com

**Comment by WinterPhoenix** [comment]
Okay. I think I may have figured out what the issue was. I'm pushing an update to GModCEFCodecFix right now; should be done in about 45 minutes. When it's done, just run the tool again, it'll grab the latest version of the patches automatically, and let us know how it goes.

**Comment by CrabbieMike** [comment]
Sweet I'll let you know what happens once it's up

**Comment by CrabbieMike** [comment]
It does work now thank you

**Comment by WinterPhoenix** [comment]
glad to hear it!
