### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by coriorh** [solsticegamestudios/GModCEFCodecFix#102]
![изображение](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/153491736/b1415e0b-3b8d-491d-9712-15f078e0ac47)

This is probably due to the repackaging of the Steam client via Snap

**Comment by WinterPhoenix** [comment]
Where is Steam located on your machine?

**Comment by coriorh** [comment]
> Where is Steam located on your machine? Is it the path detected?

By this path '/home/user/.local/share/Steam' I have "steamcmd" installed
The steam client is located '/home/user/snap/steam"

**Comment by coriorh** [comment]
I installed Steam via .deb package. Everything is working!
Sorry to bother you 😅

**Comment by WinterPhoenix** [comment]
> > Where is Steam located on your machine? Is it the path detected?
> 
> By this path '/home/user/.local/share/Steam' I have "steamcmd" installed The steam client is located '/home/user/snap/steam"

oh interesting...okay

**Comment by AkikoKumagara** [comment]
Should hopefully be working with a combo of https://github.com/solsticegamestudios/GModCEFCodecFix/pull/105 and https://github.com/solsticegamestudios/gmod-html/commit/3e7d15f914691f409696b2d874c2703610ae8f06

**Comment by WinterPhoenix** [comment]
Should be fixed as of the [latest release](https://github.com/solsticegamestudios/GModCEFCodecFix/releases)
