### ISSUE TITLE
No longer able to find Garry's Mod

### ISSUE THREAD

**Issue by roxwize** [solsticegamestudios/GModCEFCodecFix#103]
Context: I use Linux (openSUSE Tumbleweed). I had previously used this tool when I had Garry's Mod installed on an external drive and it worked perfectly. Now that the hard drive has stopped functioning and I've been forced to move the game to my home filesystem it's not working anymore. Running it normally, regardless of location, gives me this:

```
GModCEFCodecFix
Created by: Solstice Game Studios
How To Guide:
        https://www.solsticegamestudios.com/forums/threads/60/
Contact Us:
        Discord: https://www.solsticegamestudios.com/discord/
        Email: contact@solsticegamestudios.com

Getting remote version...
You are running the latest version of CEFCodecFix [Local: 20240313 / Remote: 20240313]!

Steam Path:
/home/[my user]/.local/share/Steam

Got Most Recent Steam User: roxwize (76561198300196951 / [U:1:339931223])

Found Steam Library:
/mnt/world/SteamLibrary
Error: Could Not Find Garry's Mod!

If you need help, follow the Guide first:
- https://www.solsticegamestudios.com/forums/threads/60/

If that doesn't work, contact us:
- Discord: https://www.solsticegamestudios.com/discord/
- Email: contact@solsticegamestudios.com
```

`/mnt/world/` is the previously mentioned hard drive that doesn't work anymore. I don't know why it thinks it's a Steam Library when it's not even plugged into my computer. **Garry's Mod is installed in `/home/[my user]/.local/share/Steam/steamapps/common/GarrysMod/`.** I don't know why it's not detecting it when it got the Steam path perfectly right.

**Comment by WinterPhoenix** [comment]
We just updated the tool to try and detect GMod based off of your library config.

Take a look at `Steam/steamapps/libraryfolders.vdf`, you might have app "4000" listed under more than one library

**Comment by roxwize** [comment]
Right after I posted this I reinstalled Garry's Mod and it seems to be working again.

**Comment by WinterPhoenix** [comment]
Okay cool, have fun!
