### ISSUE TITLE
Steam LoginUsers not found

### ISSUE THREAD

**Issue by riviox** [solsticegamestudios/GModCEFCodecFix#107]
![image](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/100956266/1a53e1cb-d9a5-4e65-a8f1-54e5a3f3fcb5)

**Comment by WinterPhoenix** [comment]
You likely have multiple installations of Steam, one Flatpak and one not. Since it seems like you're not using the Flatpak one, uninstall that, including removing its folders, and try again.

**Comment by riviox** [comment]
> You likely have multiple installations of Steam, one Flatpak and one not. Since it seems like you're not using the Flatpak one, uninstall that, including removing its folders, and try again.

Fixed that already

**Comment by WinterPhoenix** [comment]
Please download the latest release and try again

**Comment by WinterPhoenix** [comment]
Closing since this is stale
