### ISSUE TITLE
CEFCodecFix shows "Does Not Match Original!" for html_chromium.dll

### ISSUE THREAD

**Issue by SmileBey** [solsticegamestudios/GModCEFCodecFix#11]
whenever i tried to run the game by windows codec fix, it says:
(I already verified my gamefiles like 10 times.)
Checking Files to see what needs to be Fixed...
        bin/chrome_elf.dll: Needs Fix
        bin/html_chromium.dll: Does Not Match Original!
        bin/libcef.dll: Needs Fix
        bin/libEGL.dll: Needs Fix
        bin/libGLESv2.dll: Needs Fix
        bin/chromium/cef.pak: Needs Fix
        bin/win64/chrome_elf.dll: Needs Fix
        bin/win64/html_chromium.dll: Does Not Match Original!
        bin/win64/libcef.dll: Needs Fix
        bin/win64/libEGL.dll: Needs Fix
        bin/win64/libGLESv2.dll: Needs Fix

Error: One or More Files Failed to Match the Original Checksum!
        Please Verify Garry's Mod Integrity and Try Again!

**Comment by WinterPhoenix** [comment]
Thanks for letting us know! GMod had an update today that changed the checksums of those files.

It should be fixed now, give it another shot.

**Comment by SmileBey** [comment]
It is working now, thanks for fast reply.
