### ISSUE TITLE
not functional on steam deck

### ISSUE THREAD

**Issue by DoctorHugoSource** [solsticegamestudios/GModCEFCodecFix#111]
steam deck runs (arch) linux, executable for linux does nothing on launch, not even an error

**Comment by WinterPhoenix** [comment]
Are you running it in Terminal? Does the file have execute permission?

**Comment by DoctorHugoSource** [comment]
hold on something changed, i verified gmod,s file cache and now it strangely just works - nothing wrong with the script then, very weird...
