### ISSUE TITLE
Can't select correct Steam installation for patching Garry's Mod on Linux

### ISSUE THREAD

**Issue by hxdeci** [solsticegamestudios/GModCEFCodecFix#113]
I run Debian 12 and I have both regular Steam and Flatpak Steam installed on my system so I can run Halo Infinite. It's... a long story, but Garry's Mod is installed only to the regular Steam installation on my computer. I need the script in order to launch Garry's Mod, otherwise my menus completely break rendering the game unplayable. I already run the x64 branch of GMod (in fact, it's the only way the game functions properly for me, using the x86 version crashes on map load)
The script seems to default to the Flatpak installation of Steam, where Garry's Mod isn't installed. There's barely any documentation for the script as well, so I wasn't able to find a way to direct it to the proper Steam installation. 
Either this is a bug or a much-needed feature request.. sorry if this is an odd system setup but Flatpak is the only way Halo Infinite will run on my computer, and it has it's own set of issues so i don't want to move any more games over

```
GModCEFCodecFix
Created by: Solstice Game Studios
How To Guide/FAQ:
	https://www.solsticegamestudios.com/fixmedia/
Contact Us:
	Discord: https://www.solsticegamestudios.com/discord/
	Email: contact@solsticegamestudios.com

Getting remote version...
You are running the latest version of CEFCodecFix [Local: 20240530 / Remote: 20240530]!

Warning: Multiple Steam Installations Detected! This may cause issues:
	- /home/deci/.var/app/com.valvesoftware.Steam/.local/share/Steam
	- /home/deci/.steam/steam <--- This is where GMod should be installed
	- /home/deci/.local/share/Steam


Steam Path:
/home/deci/.var/app/com.valvesoftware.Steam/.local/share/Steam

Got Most Recent Steam User: deci (76561199019831263 / [U:1:1059565535])

Steam Libraries:
['/home/deci/.var/app/com.valvesoftware.Steam/.local/share/Steam', '/teradrive/SteamLibrary', '/teradrive/HaloInfinite']

Error: Could Not Find Valid Garry's Mod Manifest! Is Garry's Mod Installed?

If you need help, look at the Guide/FAQ first:
- https://www.solsticegamestudios.com/fixmedia/

If that doesn't work, contact us:
- Discord: https://www.solsticegamestudios.com/discord/
- Email: contact@solsticegamestudios.com

Press Enter to continue...
```

Thanks in advance :3

**Comment by WinterPhoenix** [comment]
There isn’t a way to force using a specific Steam install. You really shouldn’t have more than one copy of Steam. There’s nothing that I know of that works in Flatpak but doesn’t in the native install, so you should probably just use the native install.

The only exception for that is if you have SteamCMD installed to manage servers or whatever, which is why the script looks for Flatpak/Snap first.

**Comment by nxdeci** [comment]
I _have_ to use Flatpak Steam for Halo Infinite otherwise the game crashes on startup, even compiling all the libraries that would cause said issues on the native install doesn't fix the problem
but, Flatpak Steam has even more issues on it's own, and i'd rather not move all of my games to it. it's not something that i want to do, and i'm aware it's definitely not optimal but it's the Only solution i have, sorry

**Comment by WinterPhoenix** [comment]
Hmmm… Okay, I’ll add the ability to override the Steam install finder with a custom path. It might take a couple days but I’ll let you know when it’s done.

**Comment by WinterPhoenix** [comment]
Haven't had time to work on this yet, but rest assured it's coming

**Comment by AkikoKumagara** [comment]
> I _have_ to use Flatpak Steam for Halo Infinite otherwise the game crashes on startup, even compiling all the libraries that would cause said issues on the native install doesn't fix the problem i debugged this issue for months on end, even the official Proton GitHub issue had no answers, i was ignored but, Flatpak Steam has even more issues on it's own, and i'd rather not move all of my games to it. it's not something that i want to do, and i'm aware it's definitely not optimal but it's the Only solution i have, sorry

We've implemented a fix for Flatpak installations of GMod, at least, so if you want to move just your Garry's Mod install to the Flatpak Steam and leave everything else be, that might be a workaround for your system for now until we have a means to select which installation to patch.

**Comment by WinterPhoenix** [comment]
This has been added as of the [latest release](https://github.com/solsticegamestudios/GModCEFCodecFix/releases)

**Comment by hxdeci** [comment]
> We've implemented a fix for Flatpak installations of GMod, at least, so if you want to move just your Garry's Mod install to the Flatpak Steam and leave everything else be, that might be a workaround for your system for now until we have a means to select which installation to patch.

that's not a workaround and will never be, flatpak steam is not as stable compared to native amongst other issues which is just flatpak's problem
my real solution is to just patch the file by changing the order in which the python script searches for the game install
