### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by AlterRainytu** [solsticegamestudios/GModCEFCodecFix#114]
у меня пропала возможность выбрать chrominum

**Comment by AlterRainytu** [comment]
because I don't have a chrominum in my startup selection

**Comment by WinterPhoenix** [comment]
Have you followed the guide?
https://www.solsticegamestudios.com/fixmedia/

Вы следовали руководству?
https://www.solsticegamestudios.com/fixmedia/

**Comment by AlterRainytu** [comment]
да, и оно не ушло, у меня иза этого гарис частично умер, иза того что место  chrominum X64 / chrominum x32 у меня Launcer 64X/Launcer 32X

**Comment by WinterPhoenix** [comment]
Do you use Windows or a different operating system?

**Comment by WinterPhoenix** [comment]
Closing due to being stale
