### ISSUE TITLE
Duplications fail to load.

### ISSUE THREAD

**Issue by VocalFan** [solsticegamestudios/GModCEFCodecFix#115]
After using the installer on Windows 11, with the x86-64 build, workshop dupes seem to fail to load with the error:
`steamworks.DownloadUGC: Failed to read addon file 'C:\Program Files (x86)\Steam\steamapps\workshop\content\4000\170801406\577871834892055424_legacy.bin' for 170801406`

**Comment by WinterPhoenix** [comment]
Completely unrelated to GModCEFCodecFix. If you need help, join the [Garry's Mod Discord](https://discord.com/invite/gmod).

**Comment by VocalFan** [comment]
> Completely unrelated to GModCEFCodecFix. If you need help with GMod, join the [official Garry's Mod Discord](https://discord.com/invite/gmod).

That's why I closed it lmao.
