### ISSUE TITLE
Latest Steam Beta Update causes script to fail

### ISSUE THREAD

**Issue by JetstreamLarry** [solsticegamestudios/GModCEFCodecFix#117]
When using the Steam client Beta Update, the script errors out after the `Getting Steam AppInfo for GMod...` line, with the following message:
```
Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 448, in <module>
  File "steam/utils/appcache.py", line 73, in parse_appinfo
SyntaxError: Invalid magic, got b')DV\x07'
[24599] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!
Press Enter to continue...
```
Opting out of the Steam Beta Update allows the script to complete successfully.
According to [this](https://github.com/ValvePython/steam/pull/463#issuecomment-2196383872), it's due to changes to the format of the `appinfo.vdf` file in the latest beta.

**Comment by WinterPhoenix** [comment]
It’s gonna be fixed in the package we use for parsing app info.vdf for it to be fixed here.

See https://github.com/ValvePython/steam/issues/462

**Comment by WinterPhoenix** [comment]
This has been fixed as of the [latest release](https://github.com/solsticegamestudios/GModCEFCodecFix/releases)
