### ISSUE TITLE
chatsounds become very crackly after patching this

### ISSUE THREAD

**Issue by atmogenic** [solsticegamestudios/GModCEFCodecFix#119]
Hi, this issue is likely on the server side that i play on (meta construct) but after I used the patch of this. chatsounds on the server become crackly to the point where its like someone is using tinfoil in the background of the sound effects, I verified my files and went back into the server and my chatsounds were back to normal but due to be doing that, the patch got reverted  so im unable to get videos i requested to work.

Sorry if this is a silly thing but because almost all the words  on the server is a chatsound, it gets very annoying with the crackling and wondering if its something with the patch update.

**Comment by WinterPhoenix** [comment]
If it’s CEF-related at all, it’s probably because of this change:
https://github.com/Facepunch/gmod-html/pull/3#issuecomment-1698274372

Either way, it’s something Metastruct’s developers have to fix
