### ISSUE TITLE
Legality of GModCEFCodecFix

### ISSUE THREAD

**Issue by dextonanderson** [solsticegamestudios/GModCEFCodecFix#12]
Hi,

First, I would like to say I am not looking to get this project taken down nor do I care if this project violates licenses pertaining to the various codecs it "injects" into CEF. I enjoy this project and thank the authors for the time put into it.

I am curious though, has there been consideration into the legality of this project? I know it's probably not a big deal, especially since it's not a commercial product.

A note from the Google site on how to build CEF with proprietary codecs:
```
**Including the Chrome Proprietary Codecs**
Note that these additional codecs require various licensing agreements with and fees paid to the individual codec patent holders.
```
https://support.google.com/webdesigner/answer/10043691?hl=en

Does using a binary diff AKA bsdiff avoid the licensing agreement because it is not distributing the actual codec binary itself?

Thanks

**Comment by WinterPhoenix** [comment]
When you run GModCEFCodecFix, you download patches (the bsdiff files). After download, your computer then patches the original CEF files included with GMod. The final binaries with the features you're targeting are created by your computer, and we only distribute "guides" telling you/your computer how to patch them.

We don't create the final binaries, you do, and it's our understanding that if you were to compile CEF for yourself with proprietary codecs enabled, it would be completely legal without paying licensing fees.

All GModCEFCodecFix does is provide a shortcut to compiling CEF yourself, so you don't have to wait hours to compile the whole thing beginning to end yourself.

**Disclaimer:** This is not legal advice and I'm not a lawyer.
