### ISSUE TITLE
GModCEFCodecFix.app sometimes fails to execute (macOS)

### ISSUE THREAD

**Issue by AkikoKumagara** [solsticegamestudios/GModCEFCodecFix#120]
Because we're using the [Appify script](https://github.com/solsticegamestudios/GModCEFCodecFix/blob/master/docs/macOS/scripts/appify.sh) + [launcher script](https://github.com/solsticegamestudios/GModCEFCodecFix/blob/master/docs/macOS/scripts/launcher.sh), there are sometimes issues where some sort of permissions error arises when it attempts to launch GModCEFCodecFix in a Terminal process, so it fails with the text output in a dialog window stating that “GModCEFCodecFix-macOS” can’t be opened because (null) is not allowed to open documents in Terminal.

This has a very simple workaround of simply running the executable code directly with the following command, but this nullifies or negates some of the convenience of having the .app package in the first place. The better solution would be to figure out why this would happen and resolving it at the source of the issue.

Workaround: Run `/Applications/GModCEFCodecFix.app/Contents/MacOS/GModCEFCodecFix-macOS` in a Terminal process manually.

**Comment by WinterPhoenix** [comment]
This is an bug in Ventura 13.0 and Ventura betas. If you see this error message, update to the latest version of Ventura to fix it.

**Comment by AkikoKumagara** [comment]
> This is an bug in Ventura 13.0 and Ventura betas. If you see this error message, update to the latest version of Ventura to fix it.

Marking as closed since we have a solution already. Thanks for the info.
