### ISSUE TITLE
Do not detect "~/.steam/steam" as another Steam installation on Linux

### ISSUE THREAD

**Issue by Tiagoquix** [solsticegamestudios/GModCEFCodecFix#122]
`~/.steam/steam` is detected as one of the "multiple installations" alongside with `~/.local/share/Steam/`.

`~/.steam/steam` is a link to `~/.local/share/Steam/`.

It should not be detected as a multiple Steam install.

I'm not sure if the program tries to detect `~/.steam/root`, but it is also a link to `~/.local/share/Steam/`.

**Comment by WinterPhoenix** [comment]
`~/.steam/steam` is a legacy install location, so Steam puts symlink there even if it's installed in the new location. We should probably just be resolving symlinks so it doesn't detect them separately

**Comment by WinterPhoenix** [comment]
Should be fixed in the latest release.
