### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by DE47H** [solsticegamestudios/GModCEFCodecFix#127]
Whenever I try to run the exe this happens:
![image](https://github.com/user-attachments/assets/3853d072-486c-4d9d-8298-ba1315796419)

**Comment by DE47H** [comment]
I tried changing gmod's installation file to C: but it still won't work. I saw that there was another user who had the same problem. I should have the correct beta installation.

**Comment by WinterPhoenix** [comment]
Your localconfig.vdf is likely corrupt. Send me an email with it attached at winter@solsticegamestudios.com
