### ISSUE TITLE
"Branch of Garry's Mod is not supported!" when on correct branch.

### ISSUE THREAD

**Issue by stevenlafl** [solsticegamestudios/GModCEFCodecFix#13]
I am on the correct branch as it says as per this screen shot:
![image](https://user-images.githubusercontent.com/2539092/107096585-19011e80-67d9-11eb-87ca-96eaa1ace3a5.png)

But I get this:

![image](https://user-images.githubusercontent.com/2539092/107096715-5b2a6000-67d9-11eb-8807-2d5ff2ab154a.png)

Now I did go to the how-to guide and there is absolutely nothing on this. No information on how to patch it manually either.

```
GMod CEF Codec Fix
Created by: Solstice Game Studios
How To Guide:
        https://www.solsticegamestudios.com/forums/threads/60/
Contact Us:
        Discord: https://www.solsticegamestudios.com/chat.html
        Email: contact@solsticegamestudios.com

You are running the latest version of CEFCodecFix [Local: 20201025 / Remote: 20201025]!

Steam Path:
c:\program files (x86)\steam

Steam Libraries:
['c:\\program files (x86)\\steam', 'D:\\SteamLibrary', 'E:\\SteamLibrary']

Got Most Recent Steam User: [REDACTED]

Found Garry's Mod:
D:\SteamLibrary\steamapps\common\GarrysMod

Found Garry's Mod Manifest:
E:\SteamLibrary\steamapps\appmanifest_4000.acf

Garry's Mod Branch:
main

Getting Steam AppInfo for GMod...
        Platform: win32
        D:\SteamLibrary\steamapps\common\GarrysMod\hl2.exe
                EXE Found
GMod EXE Launch Options Detected: 1

Error: This Branch of Garry's Mod is not supported! Please switch to the x86-64 branch and then try again.
```

**Comment by WinterPhoenix** [comment]
You have more than one copy of Garry's Mod. Delete whichever one you're not using, as well as its `appmanifest_4000.acf`

**Comment by stevenlafl** [comment]
@WinterPhoenix That was it! So, I did get the warning that told me to delete one of my copies. I did delete it, but I did not delete the manifest file. I forget what the message was precisely.

Maybe that could be clarified or indeed detected and added to this message's output.

**Comment by WinterPhoenix** [comment]
There's probably a couple of tweaks we could do there; mainly just not trying to use another copy's manifest in the first place.

Glad we could figure it out for you!
