### ISSUE TITLE
add a version of this script puerly to fix the crashing issues on mac/linux

### ISSUE THREAD

**Issue by Totallynotmwa** [solsticegamestudios/GModCEFCodecFix#137]
why??   
steam overlay doesn't work
some people may not want the chromium/beta build (including me) 
thats what i can think off

**Comment by WinterPhoenix** [comment]
It fixes the crashing issues *because* this tool patches Chromium. Furthermore, the x86-64 beta is required for some platforms since they’re 64-bit only.

If you don’t want Chromium at all, which isn’t recommended because you’ll lose functionality, you can install the “Lua Main Menu” addon instead.

**Comment by Totallynotmwa** [comment]
> It fixes the crashing issues _because_ this tool patches Chromium. Furthermore, the x86-64 beta is required for some platforms (like macOS) since they’re 64-bit only.
> 
> If you don’t want Chromium at all, which isn’t recommended because you’ll lose functionality, you can install the “Lua Main Menu” addon instead.

Thanks for the follow up comment, i can understand this tool only fixes crashes because the chromium builds dont work well.

**Comment by WinterPhoenix** [comment]
There’s a bunch of reasons why Chromium in GMod causes crashes. A lot of it is just it not being up to date, which this tool fixes as well
