### ISSUE TITLE
CEFCodecFix shows "Does Not Match Original!" for many of the DLL files

### ISSUE THREAD

**Issue by LukasExemplar** [solsticegamestudios/GModCEFCodecFix#14]
GMod CEF Codec Fix
Created by: Solstice Game Studios
How To Guide:
        https://www.solsticegamestudios.com/forums/threads/60/
Contact Us:
        Discord: https://www.solsticegamestudios.com/chat.html
        Email: contact@solsticegamestudios.com

You are running the latest version of CEFCodecFix [Local: 20201025 / Remote: 20201025]!

Steam Path:
c:\program files (x86)\steam

Steam Libraries:
['c:\\program files (x86)\\steam', 'E:\\Games']

Got Most Recent Steam User: **(insert username and ID)** (I am not going to put my username here for privacy reasons).

Found Garry's Mod:
E:\Games\steamapps\common\GarrysMod

Found Garry's Mod Manifest:
E:\Games\steamapps\appmanifest_4000.acf

Garry's Mod Branch:
chromium

Getting Steam AppInfo for GMod...
        Platform: win32
        E:\Games\steamapps\common\GarrysMod\hl2.exe
                EXE Found
        E:\Games\steamapps\common\GarrysMod\bin\gmod.exe
                EXE Found
GMod EXE Launch Options Detected: 2

CEFCodecFix Manifest Loaded!
Checking Files to see what needs to be Fixed...
        bin/chrome_elf.dll: Does Not Match Original!
        bin/html_chromium.dll: Does Not Match Original!
        bin/libcef.dll: Does Not Match Original!
        bin/libEGL.dll: Does Not Match Original!
        bin/libGLESv2.dll: Does Not Match Original!
        bin/chromium/cef.pak: Does Not Match Original!
        bin/win64/chrome_elf.dll: Does Not Match Original!
        bin/win64/html_chromium.dll: Does Not Match Original!
        bin/win64/libcef.dll: Does Not Match Original!
        bin/win64/libEGL.dll: Does Not Match Original!
        bin/win64/libGLESv2.dll: Does Not Match Original!

Error: One or More Files Failed to Match the Original Checksum!
        Please Verify Garry's Mod Integrity and Try Again!

If you need help, follow the Guide first:
- https://www.solsticegamestudios.com/forums/threads/60/

If that doesn't work, contact us:
- Discord: https://www.solsticegamestudios.com/chat.html
- Email: contact@solsticegamestudios.com

Press Enter to continue...

**Comment by WinterPhoenix** [comment]
Have you verified Garry’s Mod?

**Comment by Sophie-bear** [comment]
Try using the x86-64 branch instead of the chromium branch.
