### ISSUE TITLE
steamswebhelper is not responding

### ISSUE THREAD

**Issue by Nekocmd** [solsticegamestudios/GModCEFCodecFix#141]
Hello,

I was able to run 2 Steam instances on my computer using the following commands as shared on Steam discussions:
`set VPROJECT=steammulti

start "Steam1" "C:\Program Files (x86)\Steam\steam.exe" -master_ipc_name_override steam1

start "Steam2" "C:\Program Files (x86)\Steam\steam.exe" -master_ipc_name_override steam2 -userchooser
`
It used to work perfectly fine.

After installing the Swamp Cinema codec pack, I can't run 2 Steam instances anymore.  Whenever I try to run the 2nd instance, I get that: 
steamswebhelper is not responding

How do I fix this?

Note: No, I'm not using 2 Steam to log on to Gmod, but for other games.

**Comment by WinterPhoenix** [comment]
GModCEFCodecFix doesn't have anything to do with Steam.
