### ISSUE TITLE
Mac does not match original 

### ISSUE THREAD

**Issue by benlevers121** [solsticegamestudios/GModCEFCodecFix#15]
Last login: Fri Feb 26 15:09:04 on ttys000
/Users/benlevers/Downloads/GModCEFCodecFix-macOS ; exit;                        
benlevers@Bens-iMac ~ % /Users/benlevers/Downloads/GModCEFCodecFix-macOS ; exit;
GMod CEF Codec Fix
Created by: Solstice Game Studios
How To Guide:
	https://www.solsticegamestudios.com/forums/threads/60/
Contact Us:
	Discord: https://www.solsticegamestudios.com/chat.html
	Email: contact@solsticegamestudios.com

You are running the latest version of CEFCodecFix [Local: 20201025 / Remote: 20201025]!

Steam Path:
/Users/benlevers/Library/Application Support/Steam

Steam Libraries:
['/Users/benlevers/Library/Application Support/Steam', '/Volumes/WIN 10/SteamLibrary']

Got Most Recent Steam User: Panda (76561198800001611 / [U:1:839735883])

Found Garry's Mod:
/Users/benlevers/Library/Application Support/Steam/steamapps/common/GarrysMod

Found Garry's Mod Manifest:
/Users/benlevers/Library/Application Support/Steam/steamapps/appmanifest_4000.acf

Garry's Mod Branch:
x86-64

Getting Steam AppInfo for GMod...
	Platform: darwin
	/Users/benlevers/Library/Application Support/Steam/steamapps/common/GarrysMod/hl2_osx
		EXE Found
GMod EXE Launch Options Detected: 1

CEFCodecFix Manifest Loaded!
Checking Files to see what needs to be Fixed...
	GarrysMod_Signed.app/Contents/Frameworks/Chromium Embedded Framework.framework/Chromium Embedded Framework: Does Not Match Original!
	GarrysMod_Signed.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libEGL.dylib: Does Not Match Original!
	GarrysMod_Signed.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libGLESv2.dylib: Does Not Match Original!
	GarrysMod_Signed.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libEGL.dylib: Does Not Match Original!
	GarrysMod_Signed.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libswiftshader_libGLESv2.dylib: Does Not Match Original!

Error: One or More Files Failed to Match the Original Checksum!
	Please Verify Garry's Mod Integrity and Try Again!

If you need help, follow the Guide first:
- https://www.solsticegamestudios.com/forums/threads/60/

If that doesn't work, contact us:
- Discord: https://www.solsticegamestudios.com/chat.html
- Email: contact@solsticegamestudios.com

tried verifying files and still won't work >:( im on Mac big sur so idk if that is the issue

**Comment by Sophie-bear** [comment]
Thanks for bringing this to our attention. We had an automated solution in place to deal with macOS file updates but it seems to be having problems. We're manually fixing the files now so it should work again soon.

**Comment by WinterPhoenix** [comment]
Okay, I think we've fixed the automated solution. Please let us know if you run into this again!
