### ISSUE TITLE
One or More Files Failed to Match the Original Checksum!

### ISSUE THREAD

**Issue by EmeraldWizardX** [solsticegamestudios/GModCEFCodecFix#16]
I did everything. i checked gmod's integrity, and uninstalled VLC. i have a 64 bit windows 10

**Comment by EmeraldWizardX** [comment]
using November 18th, 2019 and lower works

**Comment by Sophie-bear** [comment]
I tried to reproduce this on my end and could not. After validating GMod file integrity the latest version from Releases worked perfectly for me. Is there anything 'abnormal' about your configuration that you think could be causing issues?
Also, no need to uninstall VLC.
