### ISSUE TITLE
CEFCodecFix does not support Windows 7 due to Python being unsupported

### ISSUE THREAD

**Issue by JohanBLU** [solsticegamestudios/GModCEFCodecFix#17]
I try to open the program on my computer and I get an api-ms-win-core-path-l1-1-0.dll error. I figured out the problem after opening the program in command prompt which revealed it was trying to use the python39.dll file, which I don't have because Python version 3.9 is not supported on Windows 7. I have installed Python 3.8 btw.

**Comment by WinterPhoenix** [comment]
Windows 7 is [End of Life](https://www.microsoft.com/en-US/windows/windows-7-end-of-life-support-information). Any OS that isn't currently supported, we don't support ourselves.

You're correct that Python 3.9 doesn't support Windows 7:
> As specified in PEP 11, a Python release only supports a Windows platform while Microsoft considers the platform under extended support. This means that Python 3.9 supports Windows 8.1 and newer. If you require Windows 7 support, please install Python 3.8.

We use PyInstaller to package everything including the runtime environment (Python 3.9) into executables for easy use. You can however just run the script yourself, which is probably going to be your only option, aside from using a supported operating system.

Quick napkin instructions to do that are:
1. Download the repo
2. Run the following in the repo's folder:
```
pip install -r requirements.txt
python GModCEFCodecFix.py
```

We won't fix the release executable not working on Windows 7.

Good luck!

**Comment by jak570** [comment]
Thank you for the quick response! <3
