### ISSUE TITLE
connect through IE proxy settings?

### ISSUE THREAD

**Issue by dounai2333** [solsticegamestudios/GModCEFCodecFix#18]
I'm not sure if I describe it correctly, but I'm having bad network with my wifi connection and it just took too many times to run the program.
I got a my person vps server to speed up my connection with worldwide, and I'm using IE proxy PAC setting to filter some website i need or no need to through vps.
so, current program are using direct connection to the github instead of pass through default proxy which slow down too much (really too much)
![P$_XH{)N95}1D`PZ~PN}$ 3](https://user-images.githubusercontent.com/45044404/128641320-883f8131-2a16-451a-bb93-b5541904cd98.png)
I can even have a nap for 15min, I already has a bat script to replace files manually instead of run the program, but I will lost the latest updates from here, is it possible to do support in future?

here is where I'm doing with the IE proxy:
![d5c2cc2c747fdd1b35f62201b8845309_lan_settings_button_internet_explorer_screenshot](https://user-images.githubusercontent.com/45044404/128641497-c70ec0a2-294e-47a7-9035-c74d93dbb985.png)

**Comment by WinterPhoenix** [comment]
Why not just use a regular VPN? If you have a VPS already, you could set up WireGuard on it and then just put all of your internet traffic through there. Although it’s much more difficult to control what goes through the VPN and what doesn’t.

I guess I can look into it but old-fashioned Proxies tend to not be quite as stable or reliable.

**Comment by dounai2333** [comment]
> Why not just use a regular VPN? If you have a VPS already, you could set up WireGuard on it and then just put all of your internet traffic through there. Although it’s much more difficult to control what goes through the VPN and what doesn’t.
> 
> I guess I can look into it but old-fashioned Proxies tend to not be quite as stable or reliable.

thanks for the reply, yes I already have a backup plan which is what you talked about, and also as you said I can't do for the filter so I don't want to use it too much (it cause lagging come from my country because the vps server isn't running in my country)

sadly I don't have knowledge about python or I'll choice do it myself. whatever you gonna do thanks in advance!

**Comment by dounai2333** [comment]
or a more positive and possible solution: make a offline version which save needed files to the local PC to solve "who has a bad network or without network", and leave a text to tell user where to get latest update, it's not too hard to make one I guess

**Comment by WinterPhoenix** [comment]
Hey dounai, I've sent you a friend request on Discord. I have a version of CEFCodecFix with proxy support that I'd like you to try.

**Comment by WinterPhoenix** [comment]
Support for this has been added in the latest release. Thanks!
