### ISSUE TITLE
Program detects duplicate steam library folder that doesn't exist

### ISSUE THREAD

**Issue by JohanBLU** [solsticegamestudios/GModCEFCodecFix#19]
Like... 2 of the library folders are the exact same. Idk if this is steam but this is weird. I already checked libraryfolders.vdf in the C: steam folder and found that yes it was the same thing duplicated but setup like a new folder, already deleted one of them but it didnt seem to do anything.

Here are logs of the CEFCodecFix program. I'm also on Windows 10 if that helps.

![image](https://user-images.githubusercontent.com/61067492/129504409-d716e212-112f-4e68-8026-e8395ef5a3e5.png)

**Comment by WinterPhoenix** [comment]
That's super weird. I'm going to assume it's a misconfigured `libraryfolders.vdf` manifest. I'll add a check to make sure duplicates don't make it in.

**Comment by WinterPhoenix** [comment]
This has been fixed in the latest release. Thanks!
