### ISSUE TITLE
windows cannot access the specified decide path or file. you may not have the appropriate permissions to access the item,

### ISSUE THREAD

**Issue by Meweu** [solsticegamestudios/GModCEFCodecFix#20]
![Screenshot 2021-09-24 221142](https://user-images.githubusercontent.com/70145891/134754439-5f0cb770-031d-4fcc-9ffa-8fc7432eb6f6.png)

**Comment by WinterPhoenix** [comment]
Almost certainly going to be Antivirus interfering.

**Comment by Meweu** [comment]
> Almost certainly going to be Antivirus interfering.

just relized, it thinks its malware for some reason

**Comment by WinterPhoenix** [comment]
If you're using Windows Defender, it should work fine. We can't promise other antivirus won't falsely detect it as malware.
