### ISSUE TITLE
Not Working on windows 7

### ISSUE THREAD

**Issue by jak570** [solsticegamestudios/GModCEFCodecFix#21]
I have a problem when starting the exe file in windows 7, it doesn't start at all. I had the same issue in the last update so I had to use the "June 28th, 2021" version that works on my computer, but not any more since this update :(

Please fix!

**Comment by WinterPhoenix** [comment]
GModCEFCodecFix's release executables do not support Windows 7.

See https://github.com/solsticegamestudios/GModCEFCodecFix/issues/17
