### ISSUE TITLE
Phyton Error

### ISSUE THREAD

**Issue by Nicolassc2** [solsticegamestudios/GModCEFCodecFix#22]
Hi, I'm having this problem since the codecs were put into this program. When i'm trying to open the program i get this error to which i have not found any solution at the moment. What could i do in this case?
![GMOD Phyton Error](https://user-images.githubusercontent.com/75028182/147120650-9cad00a1-1655-4ed3-a91f-306d0b77dd79.JPG)

**Comment by WinterPhoenix** [comment]
Windows 7 is not supported.

See #17

**Comment by Nicolassc2** [comment]
Ok, ty. Before closing the issue, What does "repo" mean?

**Comment by WinterPhoenix** [comment]
Repo is slang for repository
