### ISSUE TITLE
urgent

### ISSUE THREAD

**Issue by KillswordEngagE** [solsticegamestudios/GModCEFCodecFix#25]
ok so I play Swamp Cinema often, but ive been having issues regarding the codecs. The most up to date codex seems to break my game and completely disable my Nivida gpu from working at all during gameplay. This would not be a problem if not for the need to have a higher frame rate. ive done eveything i could think to fix and the only thing that works is to revalidate the game files and use an older version of the codex.

**Comment by Sophie-bear** [comment]
Can you explain exactly what the issue entails? I'm not sure why or how GModCEFCodecFix would be the cause of your GPU not working in-game.
Launching the game just uses your iGPU instead of the GeForce one?

**Comment by WinterPhoenix** [comment]
What OS are you using? Also, please provide screenshots, output of CEFCodecFix, or *anything* that would help us narrow this down.

**Comment by KillswordEngagE** [comment]
so i play via an external hard drive, and everything runs smooth, my nvidia gpu detects im playing gmod and everything but as soon as i install the up to date codecs im certain it changes enough files where nvidia detects im playing something else other than a game it can support. i will add screenshots as soon as im awake enough to.

**Comment by KillswordEngagE** [comment]
also my operating system is windows 10

**Comment by WinterPhoenix** [comment]
Could you Verify Game Integrity and then try re-running the script? We updated some things yesterday

**Comment by WinterPhoenix** [comment]
Closing do to inactivity.
