### ISSUE TITLE
Fix CEF on Arch Linux w/ glibc 2.35

### ISSUE THREAD

**Issue by ghost** [solsticegamestudios/GModCEFCodecFix#26]
Someone found a [workaround](https://github.com/Facepunch/garrysmod-issues/issues/5166#issuecomment-1062167035)

**Comment by WinterPhoenix** [comment]
Try the latest version of GModCEFCodecFix, deployed yesterday.

**Comment by GNUmod** [comment]
So I need to clone git repository?

**Comment by WinterPhoenix** [comment]
No. Just run the tool from Releases

**Comment by GNUmod** [comment]
Doesn't work. Game menu does not appear.

**Comment by WinterPhoenix** [comment]
Did you verify Game Integrity before running the tool?

Are you on Arch?

Do you have user namespaces enabled in your kernel (`CONFIG_USER_NS`)?

Do you have any other gotchas fixed for user namespaces?
See "Unprivileged containers on linux-hardened and custom kernels" in https://wiki.archlinux.org/title/Linux_Containers

What does your chromium.log have to say about it?

**Comment by GNUmod** [comment]
Yes, the tool reminded me of this.

Artix but I think there is no difference.

Don't know what it is but I use linux-tkg with modprobed-db. Maybe it didn't turn on? I'll try vanilla kernel later.

Deleted old chromium.log and it no longer appears. Did i do something wrong?

And yet when I use [this fix](https://github.com/Facepunch/garrysmod-issues/issues/5166#issuecomment-1062167035) , everything works for me.

**Comment by GNUmod** [comment]
Tried vanilla kernel and menu still doesn't appear.

**Comment by WinterPhoenix** [comment]
If chromium.log isn't being written anymore after deleting it, that sounds like either CEF is failing to init to the point that it can write log files, or a permissions issue.

I don't much more insight into this at the moment. However, I'm seeing the same issue with SteamOS (based on Arch) on the Steam Deck. CEF works with x86-64, but not after CEFCodecFix is applied.

We'll probably end up looking further into it at some point. We want to make sure it works on SteamOS/Steam Deck.

**Comment by GNUmod** [comment]
After a long time, I found a solution to the problem why this fix did not help run Chromium. The problem was simple! Just don't use Steam Linux Runtime in game options (I used it to fix cyrillic fonts).

**Comment by WinterPhoenix** [comment]
Try running the tool again. I think the problem should be solved as of Commit 8589422
