### ISSUE TITLE
Arch Linux: Library FileNotFoundError

### ISSUE THREAD

**Issue by UltraBlackLinux** [solsticegamestudios/GModCEFCodecFix#27]
Hey there,
I just tried to use this program, but it turns out that there are some issues: 
```
CEFCodecFix Manifest Loaded!
Checking Files to see what needs to be Fixed...
	bin/linux32/chromium/cef.pak: Needs Fix
	bin/linux32/chromium/cef_100_percent.pak: Needs Fix
	bin/linux32/chromium/cef_200_percent.pak: Needs Fix
	bin/linux32/chromium/cef_extensions.pak: Needs Fix
	bin/linux32/chromium/chrome_100_percent.pak: Does Not Match Original!
	bin/linux32/chromium/chrome_200_percent.pak: Does Not Match Original!
	bin/linux32/chromium/devtools_resources.pak: Needs Fix
	bin/linux32/chromium/resources.pak: Does Not Match Original!
	bin/linux64/swiftshader/libEGL.so: Does Not Match Original!
	bin/linux64/swiftshader/libGLESv2.so: Does Not Match Original!
	bin/linux64/chrome-sandbox: Does Not Match Original!
	bin/linux64/chromium_process: Needs Fix
	bin/linux64/html_chromium_client.so: Needs Fix
	bin/linux64/icudtl.dat: Needs Fix
	bin/linux64/libcef.so: Needs Fix
	bin/linux64/libEGL.so: Needs Fix
	bin/linux64/libGLESv2.so: Needs Fix
Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 414, in <module>
  File "concurrent/futures/_base.py", line 586, in result_iterator
  File "concurrent/futures/_base.py", line 425, in result
  File "concurrent/futures/_base.py", line 384, in __get_result
  File "concurrent/futures/thread.py", line 56, in run
  File "GModCEFCodecFix.py", line 398, in determineFileIntegrityStatus
  File "GModCEFCodecFix.py", line 384, in getFileSHA256
FileNotFoundError: [Errno 2] No such file or directory: '/home/maus/.steam/steam/steamapps/common/GarrysMod/bin/linux64/libvk_swiftshader.so'
```
I was already facing another issue with it not finding a library in the swiftshader directory, but appeared to be in the parent (linux64) directory, so I just linked the swiftshader folder to linux64, but then I got the error above. That library is nowhere to be found.

I managed to track down the other missing files from an unrelated program, so now the program executes, but has problems with checksums. The missing files were: vk_swiftshader_icd.json, libvulkan.so.1, libvk_swiftshader.so

Why is all of this an issue?
Thanks!

**Comment by Sophie-bear** [comment]
Hey there, I'm unable to reproduce this on Arch Linux.
Try the following:

1. Delete the directory `/home/maus/.steam/steam/steamapps/common/GarrysMod/bin/linux64/` entirely.
2. Validate your game files via Steam.
3. Run the executable again.

**Comment by UltraBlackLinux** [comment]
Well, I am massively confused about what is related to what, but now it works.
I had previously validated the files multiple times and even deleted the folder, but nothing changed. Now it works.... ???
