### ISSUE TITLE
Game showing a broken UI upon launch.

### ISSUE THREAD

**Issue by BlackFrankFTM2** [solsticegamestudios/GModCEFCodecFix#33]
My friend bought an M2 MacBook Pro and decided to buy GMOD after seeing that all of us in our friend group are playing it.
We downloaded this patch and it worked the first time around. She decided to subscribe to a few addons and launched the game, only this time the UI was broken. We unsubbed from the addons to see if they could be causing an issue. Yet relaunching the game gave us a broken UI.

Is there a fix for this? And, does Multiplayer work on x86-64 Chromium binaries to play with regular PC players? I'm hoping she didn't blow money on this game just for nothing.
Attached below are the pictures, the Mac is running macOS Monterey 12.4. If you need more information, I'll happily provide it when needed, thanks!

![image](https://user-images.githubusercontent.com/26755081/179384720-8ac480a9-1c4d-42d5-8d66-7741bdc53058.png)
![image](https://user-images.githubusercontent.com/26755081/179384724-50c6553d-036e-41cc-a362-f6a2c9fec919.png)

**Comment by AkikoKumagara** [comment]
It should be as simple as closing the game and relaunching it a few times, preferably through the GModCEFCodecFix executable each time.
I don't think we've tracked down why CEF fails to start in macOS GMod sometimes yet, but it shouldn't happen every time.
Unfortunately, I think that's the most we can do right now. I'll play with it a bit and see if I can figure anything better out.

**Comment by AkikoKumagara** [comment]
Hey, I forgot to update you but this has been fixed as of #41 if you'd like to try again!
