### ISSUE TITLE
Doesn't see URxvt as a terminal

### ISSUE THREAD

**Issue by thennothinghappened** [solsticegamestudios/GModCEFCodecFix#37]
not entirely sure what's happened here or if I've set something up incorrectly at some point recently, but the fixer doesn't see URxvt as a terminal and launches a second instance of it to run in. works after that, but I'm not sure why it thinks I'm running it from somewhere other than a terminal.
![image](https://user-images.githubusercontent.com/35243139/189463421-450d8599-f911-4b5d-a23b-b301de7613c9.png)

**Comment by WinterPhoenix** [comment]
I think it's gonna be an issue where your terminal doesn't spawn processes with itself as the parent. Not really a way to fix that, it's just kind of a quirk of how your terminal works
