### ISSUE TITLE
Mounting files from addons & Symlinks Not working

### ISSUE THREAD

**Issue by TangoDown** [solsticegamestudios/GModCEFCodecFix#39]
I am Running Linux Mint the issue I am having issues with Symbolic Links stop working

I currently have SymLinks for 

- steamapps/workshop/content/4000
- steamapps/common/GarrysMod/garrysmodf/addons
- steamapps/common/GarrysMod/garrysmodf/cache
- steamapps/common/GarrysMod/garrysmodf/data
- steamapps/common/GarrysMod/garrysmodf/cfg

Before I Installed GmodCEFCodecFix I connected to my server and all the SymLinks seemed to work Fine (was able to exec custom config files, content that was manually added to the Addons Folder Loaded)

After it would appear that the content/4000 and cache still work (as Gmod didn't try to re-download them) but data/cfg and addons no longer seem to be there.

Edit: just to be sure it wasn't the SymLinks I copied all the files over to the proper locations no SymLinks all files where they should be and it still won't recognize files inside gmod (cfg/autoexec.cfg)

**Comment by TangoDown** [comment]
I Figured it out. not sure why but Before CEF Codec Fix capitalization didn't seem to matter ( loaded just fine) after I install  CEF Codec Fix it dose. Some how came to me while I was trying to fall asleep of all places.

**Comment by WinterPhoenix** [comment]
I have no idea why CEFCodecFix would affect whether or not anything cares about case-sensitivity, but considering you're on Linux, that's a consideration due to the filesystems that tend to be used.

Sounds like you've resolved the issue yourself in either case, so I'll go ahead and close this issue.
