### ISSUE TITLE
Fixed problem for macOS with menu not loading correctly 

### ISSUE THREAD

**Issue by CarlosFelipeArantes** [solsticegamestudios/GModCEFCodecFix#41]
Hello everyone!

For the problem when the menu doesn't load properly, I've come up with a workaround.

This is the following error:

[HTML] asset://garrysmod/html/js/thirdparty/angular.js:60: ReferenceError: util is not defined
    at c.MenuController (asset://garrysmod/html/js/menu/control.Menu.js?2:159:14)
    at d (asset://garrysmod/html/js/thirdparty/angular.js:27:127)
    at Object.instantiate (asset://garrysmod/html/js/thirdparty/angular.js:27:257)
    at asset://garrysmod/html/js/thirdparty/angular.js:50:309
    at asset://garrysmod/html/js/thirdparty/angular.js:42:21
    at m (asset://garrysmod/html/js/thirdparty/angular.js:6:311)
    at o (asset://garrysmod/html/js/thirdparty/angular.js:41:390)
    at e (asset://garrysmod/html/js/thirdparty/angular.js:38:28)
    at asset://garrysmod/html/js/thirdparty/angular.js:37:118
    at asset://garrysmod/html/js/thirdparty/angular.js:15:314

The following file control.Menu.js inside /html/js/menu was changed in the following line(159) from:

            available: util.MotionSensorAvailable(),

To:

            available: false,

Since the MotionSensorAvailable function always returns false, I've removed the util so that there is no uncaught ReferenceError.

Also, I've removed the following lines starting from 187:

util.MotionSensorAvailable( function( available ) {
		$scope.kinect.available = available;
	} );

**Comment by CarlosFelipeArantes** [comment]
@AkikoKumagara this solves the following issue:

"There is also an issue specific to macOS native version that may require you to launch multiple times (through said executable, please) before CEF properly loads. We're not sure why this is at the moment. If not that, it may be an issue with codesign, which is something we'll need to investigate further."

**Comment by AkikoKumagara** [comment]
Thanks for your help. I'll take a look as soon as I can and have already forwarded this issue thread to @WinterPhoenix

**Comment by AkikoKumagara** [comment]
I was able to verify to the best of my ability that this does resolve the problem! Thanks again. We'll likely have to patch this file with the changes to resolve this for all macOS users, as I don't see a better way of addressing it currently...
