### ISSUE TITLE
Unknown VDF_VERSION: 0x07564428

### ISSUE THREAD

**Issue by Zushy** [solsticegamestudios/GModCEFCodecFix#43]
Found Garry's Mod:
c:\steam\steamapps\common\GarrysMod

Found Garry's Mod Manifest:
c:\steam\steamapps\appmanifest_4000.acf

Garry's Mod Branch:
x86-64

Getting Steam AppInfo for GMod...
Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 359, in <module>
  File "steamfiles\appinfo.py", line 29, in load
  File "steamfiles\appinfo.py", line 42, in loads
  File "steamfiles\appinfo.py", line 102, in decode
ValueError: Unknown VDF_VERSION: 0x07564428
[17004] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!
Press Enter to continue...

**Comment by WinterPhoenix** [comment]
Known issue, see https://github.com/leovp/steamfiles/issues/22 and https://github.com/ValvePython/steam/issues/418

Until we get an update out, opt-out of the Steam Client Beta and then restart Steam as a temporary fix.

**Comment by jtfen86** [comment]
Oh, I was about to report this. Doesn't work either if you patch first then change to Steam Beta.

**Comment by AkikoKumagara** [comment]
> Oh, I was about to report this. Doesn't work either if you patch first then change to Steam Beta.

If you patch first, switch to beta, then just launch the game directly (not using CEF Codec Fix as a launcher anymore), it should be fine from then on until the patched files are overwritten or updated by Steam or Facepunch.
