### ISSUE TITLE
Crashing on Startup (Arch Linux)

### ISSUE THREAD

**Issue by UmJammerRammy** [solsticegamestudios/GModCEFCodecFix#46]
64 bit branch launches before applying the fix, albeit with no menu, but crashes on the initial blue loading screen with the fix applied

**Comment by UmJammerRammy** [comment]
leaving libcef.so unpatched makes the game playable again, albeit still with no menu

**Comment by AkikoKumagara** [comment]
Check console and `chromium.log` (found in the garrysmod directory) for relevant errors and report back, please. I have the game installed on Arch with no such problem.

**Comment by SpaciousCoder78** [comment]
> 64 bit branch launches before applying the fix, albeit with no menu, but crashes on the initial blue loading screen with the fix applied
im having the same issue

**Comment by UmJammerRammy** [comment]
reinstalled gmod on linux and installed the new version of the fix and now everything seems to be working? sorry for the mostly useless issue, not sure what changed

**Comment by AkikoKumagara** [comment]
> reinstalled gmod on linux and installed the new version of the fix and now everything seems to be working? sorry for the mostly useless issue, not sure what changed

Probably just had a corrupt file or something. It can happen.

**Comment by WinterPhoenix** [comment]
Closing since it seems it resolved itself.
