### ISSUE TITLE
How to install on linux

### ISSUE THREAD

**Issue by SpaciousCoder78** [solsticegamestudios/GModCEFCodecFix#47]
In the releases window, the linux one doesnt mention any file format and is not openable by default. 
Like windows version has exe format but linux one doesnt have any format. Is there a workaround for it?

![image](https://user-images.githubusercontent.com/88923986/213234972-7f4dc5f3-6bad-4858-8ccf-e885933e7667.png)

**Comment by WinterPhoenix** [comment]
The Linux one is just a binary executable you run with `./GModCEFCodecFix-Linux` in a terminal. If you can't run it, it's probably missing the executable permission, so just do `chmod +x GModCEFCodecFix-Linux` and then try again

**Comment by AkikoKumagara** [comment]
The Readme has a link to step-by-step guides for all three versions, under "[How to use](https://github.com/solsticegamestudios/GModCEFCodecFix#-how-to-use)".
Since I saw you commented on another issue, I believe you may have gotten past this part by now. Validate your game files and try patching again if you're still having a problem.

**Comment by Munoida** [comment]
> The Linux one is just a binary executable you run with `./GModCEFCodecFix-Linux` in a terminal or however. If you can't run it, it's probably missing the executable permission, so just do `chmod +x GModCEFCodecFix-Linux` and then try again

you dont even have to do that with the terminal, you can just go to the files properties and click on "executable as program" like this 
![image](https://user-images.githubusercontent.com/84733553/213883219-53d649a1-66ff-44da-b927-12fdcc630645.png)

and then you can open it like a normal app.
![image](https://user-images.githubusercontent.com/84733553/213883238-f9bf4ffd-d239-4a6a-b54d-5c078cf0244f.png)

**Comment by AkikoKumagara** [comment]
> > The Linux one is just a binary executable you run with `./GModCEFCodecFix-Linux` in a terminal or however. If you can't run it, it's probably missing the executable permission, so just do `chmod +x GModCEFCodecFix-Linux` and then try again
> 
> you dont even have to do that with the terminal, you can just go to the files properties and click on "executable as program" like this ![image](https://user-images.githubusercontent.com/84733553/213883219-53d649a1-66ff-44da-b927-12fdcc630645.png)
> 
> and then you can open it like a normal app. ![image](https://user-images.githubusercontent.com/84733553/213883238-f9bf4ffd-d239-4a6a-b54d-5c078cf0244f.png)

That's not universal like the terminal solution is, though.

**Comment by Munoida** [comment]
> > > The Linux one is just a binary executable you run with `./GModCEFCodecFix-Linux` in a terminal or however. If you can't run it, it's probably missing the executable permission, so just do `chmod +x GModCEFCodecFix-Linux` and then try again
> > 
> > 
> > you dont even have to do that with the terminal, you can just go to the files properties and click on "executable as program" like this ![image](https://user-images.githubusercontent.com/84733553/213883219-53d649a1-66ff-44da-b927-12fdcc630645.png)
> > and then you can open it like a normal app. ![image](https://user-images.githubusercontent.com/84733553/213883238-f9bf4ffd-d239-4a6a-b54d-5c078cf0244f.png)
> 
> That's not universal like the terminal solution is, though.

it's not? huh, guess you learn something new everyday, there's probably always a way to do so within any desktop environment anyway through the gui.

**Comment by SpaciousCoder78** [comment]
I did that on Ubuntu 22.04 LTS but the file wasnt working. Do I have to use another version of ubuntu or something?

**Comment by Munoida** [comment]
> I did that on Ubuntu 22.04 LTS but the file wasnt working. Do I have to use another version of ubuntu or something?

Did it say anything when you tried to open it, via the terminal and/or gui?
