### ISSUE TITLE
Menu options disappear and errors in console on Linux

### ISSUE THREAD

**Issue by Zeppperoni** [solsticegamestudios/GModCEFCodecFix#48]
Hi SGS dev,

I'm having the following issue when applying the patch to the x64 branch of good using the GmodCEFCodexFix.

After applying the patch successfully, when loading into Gmod no launch options appear.
![1 1](https://user-images.githubusercontent.com/63176507/213935886-511973ae-1b90-4319-ba44-457ebf0a3503.png)

I am able to open the console and the following errors come up in the console when the game loads.
It should be noted I have tried to install Gmod locally and on an external drive. Logs below show the external drive.

```
Attempting to load Chromium...
 failed to dlopen /run/media/mmcblk0p1/steamapps/common/GarrysMod/bin/linux64/html_chromium_client.so error=/run/media/mmcblk0p1/steamapps/common/GarrysMod/bin/linux64/libcef.so: undefined symbol: cupsEnumDests
Failed to load /run/media/mmcblk0p1/steamapps/common/GarrysMod/bin/linux64/html_chromium_client.so: (null)
Failed to load /run/media/mmcblk0p1/steamapps/common/GarrysMod/garrysmod/bin/html_chromium_client.so: (null)
 failed to dlopen html_chromium_client.so error=/run/media/mmcblk0p1/steamapps/common/GarrysMod/bin/linux64/libcef.so: undefined symbol: cupsEnumDests
Failed to load html_chromium_client.so: (null)
Attempting to load Awesomium...
Failed to load /run/media/mmcblk0p1/steamapps/common/GarrysMod/bin/linux64/html_awesomium_client.so: (null)
Failed to load /run/media/mmcblk0p1/steamapps/common/GarrysMod/garrysmod/bin/html_awesomium_client.so: (null)
Failed to load html_awesomium_client.so: (null)
Attempting to load Stub...
x86-64: gmod_mcore_test=1
Parent cvar in server.dll not allowed (p2p_enabled)
Parent cvar in server.dll not allowed (props_break_max_pieces)
Did not detect any valid joysticks.
JOY_AXIS_X:  mapped to Turn (absolute)
JOY_AXIS_Y:  mapped to Look (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Forward (absolute)
JOY_AXIS_U:  mapped to Side (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Not playing a local game.
DEBUG: Clearing CSoundPatches after soundsound...
Addons have changes - remounting
```
Files in question can be found in the path /home/deck/.local/share/Steam/steamapps/common/GarrysMod/bin/linux64/
![Screenshot_20230122_143924](https://user-images.githubusercontent.com/63176507/213936535-8902c7db-aada-4855-8ec0-465cc0b7107d.png)

```
(127)(deck@steamdeck linux64)$ sha256sum libcef.so 
201fe5cd0e7c85a557c5a1c2a8d4f6c6c6c5d7ff06809b664ffb6ba7e526e428  libcef.so
(deck@steamdeck linux64)$ sha256sum html_chromium_client.so 
78d6aef132f69282295ddbb1923fe05dc74bdaad7b674788f9652cc0fdb140cf  html_chromium_client.so
```

After researching the issue for some time I was able to find that the CEFC code patch should resolve the issue however, it no longer does for me. Here is an example of this issue occurring in the past, but it seemed like it was resolved. 
https://github.com/Facepunch/garrysmod-issues/issues/5166

I was able to find a thread that recommended using https://github.com/robotboy655/gmod-lua-menu
This does fix the menu but chromium does not load so no videos can play.
Image of menu fixing:
![1 2](https://user-images.githubusercontent.com/63176507/213936149-1051540b-c7e8-4317-9003-941cb7f367b2.png)

Image of videos being broken when loading into a server:
![Screenshot_20230122_143422](https://user-images.githubusercontent.com/63176507/213936339-1094efe4-98c2-4b85-a49d-6d10998ff533.png)

Any support would be greatly appreciated.

~Zep

**Comment by WinterPhoenix** [comment]
This is probably the same issue as #32 . Try the workaround in there and let us know if it works

**Comment by Zeppperoni** [comment]
> This is probably the same issue as #32 . Try the workaround in there and let us know if it works

The command provided in this thread worked perfectly

`sudo cp /usr/lib64/libcups.so.2 ~/.local/share/Steam/steamapps/common/GarrysMod/bin/linux64/libcups.so.2`

**Comment by AkikoKumagara** [comment]
@WinterPhoenix is attempting to make a build that resolves the manual intervention required to fix this currently by removing the need for cups entirely, along with some other improvements for Steam Deck users. This will be a good step to help many native Linux build players enjoy the game.

**Comment by Zeppperoni** [comment]
> @WinterPhoenix is attempting to make a build that resolves the manual intervention required to fix this currently by removing the need for cups entirely, along with some other improvements for Steam Deck users. This will be a good step to help many native Linux build players enjoy the game.

thanks for the information!

A suggestion I may offer for future builds of the Linux branch users is optionally enabling the Vulkan options for gmod, I'm seeing 20-30% improvement in most cases on the deck with the following options. 

Original thread: https://www.reddit.com/r/linux_gaming/comments/xzzolt/i_got_garrys_mod_native_working_using_dxvknative/

**Comment by AkikoKumagara** [comment]
> > @WinterPhoenix is attempting to make a build that resolves the manual intervention required to fix this currently by removing the need for cups entirely, along with some other improvements for Steam Deck users. This will be a good step to help many native Linux build players enjoy the game.
> 
> thanks for the information!
> 
> A suggestion I may offer for future builds of the Linux branch users is optionally enabling the Vulkan options for gmod, I'm seeing 20-30% improvement in most cases on the deck with the following options.
> 
> Original thread: https://www.reddit.com/r/linux_gaming/comments/xzzolt/i_got_garrys_mod_native_working_using_dxvknative/

Way ahead of you 😊

**Comment by Zeppperoni** [comment]
I may have spoken a bit too soon. The following error comes up in the console on the x64 branch with the patches

`SetLocale('en_US.UTF-8') failed. Using 'LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;LC_NAME=en_US.UTF-8;LC_ADDRESS=en_US.UTF-8;LC_TELEPHONE=en_US.UTF-8;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATION=en_US.UTF-8'. You may have limited glyph support. Please install 'en_US.UTF-8' locale.`

I can confirm my locale file contains en_US.UTF-8

Attempted the following to resolve the error

`
sudo steamos-readonly disable
sudo pacman-key --init
sudo pacman-key --populate archlinux
sudo pacman -S glibc
sudo steamos-readonly enable
`

no luck... I checked a few other posts but no one else seems to have this error here.
Other folks mention the UTF-8 has been broken for a while on the x64 branch 

https://www.reddit.com/r/gmod/comments/omswdw/locale_issues_in_64_bit_version/

**Comment by WinterPhoenix** [comment]
The locale thing is a separate issue, with GMod and not CEF. Also AFAIK it’s just a detection problem

**Comment by WinterPhoenix** [comment]
Marking as duplicate; #32 is solved, so this should also be
