### ISSUE TITLE
Not working on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by SpaciousCoder78** [solsticegamestudios/GModCEFCodecFix#50]
I tried to run the script as directed in ubuntu 22.04 but nothing works. I even tried the command line method but it says invalid command. Do I have to downgrade to 20.04 as its mentioned that the file is targetted towards 20.04 in the latest release?

**Comment by AkikoKumagara** [comment]
No. Can you provide a screenshot of you attempting to run it?

**Comment by SpaciousCoder78** [comment]
Unfortunately I uninstalled Ubuntu yesterday so I can't do that i guess

**Comment by SpaciousCoder78** [comment]
I will try installing ubuntu 20.04 and try it again

**Comment by AkikoKumagara** [comment]
[My video](https://www.youtube.com/watch?v=Nsilmi0YiWw) may help if you might be getting stuck on some specific step. The error you're getting just sounds like you're attempting to run a command from the wrong directory or something of that nature.
