### ISSUE TITLE
Weird game resolution after applying patch

### ISSUE THREAD

**Issue by blcokpl** [solsticegamestudios/GModCEFCodecFix#52]
After starting the game with the patch the resolution was automatically set to 5120x1440 (I have 2 2560x1440 monitors) with the only other 16:9 option being 1920x1080, but after setting the game to 1080p, it still had a problem (I have to move the cursor to the right to click anything on the GUI. After setting the display mode to borderless window, the game was between the 2 screens (like one half was on the left monitor and the second was on the right)
Operating system: Arch Linux (with the regular 6.2.8 kernel)
Screenshot: with borderless windowed mode
![Screenshot_2023_03_25_18:03:42](https://user-images.githubusercontent.com/125572935/227732862-3bf5fa54-2275-4b17-bf10-168e8a7d63ed.png)
Sorry if I have bad English.

**Comment by AkikoKumagara** [comment]
This is a bug with GMod's x86-64 branch w/ multiple monitors on Linux, not the patch.
See [here](https://github.com/Facepunch/garrysmod-issues/issues/5326).
