### ISSUE TITLE
Menu still doesnt show intel MacOS

### ISSUE THREAD

**Issue by FredsMedia** [solsticegamestudios/GModCEFCodecFix#54]
Hey Guys!
I applied the patch for the first time today and when I opened GMod from the executable, the main menu still doesn't show up.
Would it make a difference that gmod is installed on an external SSD (through steam)?
It is on the x86_64 beta and i have an intel mac.
Provided is a screenshot of the menuless main menu and a screenshot of the successful patch.
![Screenshot 2023-04-10 at 9 24 18 am](https://user-images.githubusercontent.com/106362296/230801267-691845cb-6412-4679-9c3f-d0cf3ae7d0ae.png)
<img width="697" alt="Screenshot 2023-04-10 at 9 24 55 am" src="https://user-images.githubusercontent.com/106362296/230801308-3e939e12-f2cd-4783-9a80-8558cc70489c.png">

Thanks!

-FredsMedia

**Comment by WinterPhoenix** [comment]
What version of macOS are you on? Can you post your chromium.log file?

**Comment by FredsMedia** [comment]
> What version of macOS are you on? Can you post your chromium.log file?

I am on MacOS Ventura 13.2.1 (22D68).

Where would i find the chromium.log file and should I paste the contents straight into github or just add the file as an attachment?

**Comment by AkikoKumagara** [comment]
> 

it's in the game directory (steamapps\common\GarrysMod). You can get to this easily by right clicking the game title in your Steam games list and clicking "Manage > Browse Local Files" from the context menu.

**Comment by FredsMedia** [comment]
I don't have that file there...
<img width="1032" alt="Screenshot 2023-04-11 at 8 49 45 am" src="https://user-images.githubusercontent.com/106362296/231013659-886f3c46-1520-461e-b0fb-d897101c0c2c.png">
<img width="1032" alt="Screenshot 2023-04-11 at 8 49 13 am" src="https://user-images.githubusercontent.com/106362296/231013676-35df1fcb-8bd1-446b-a541-ef8705167079.png">

**Comment by Spritzerland** [comment]
Use gmod-lua-menu

**Comment by FredsMedia** [comment]
> Use gmod-lua-menu

Why? This version seems a lot better if we get it to work.

**Comment by Spritzerland** [comment]
on m1 macs, it doesn't show the menu, but if you use gmod-lua-menu then it shows

**Comment by Spritzerland** [comment]
I FOUND IT
REMOVE ``-nochromium`` FROM LAUNCH OPTIONS

**Comment by AkikoKumagara** [comment]
> Why? This version seems a lot better if we get it to work.
This is better, as GMod Lua menus are workarounds rather than solutions.
Do check if you have `-nochromium` in your launch options and remove it if you do, though. That part is sound advice.

**Comment by FredsMedia** [comment]
Thank you @Spritzerland and others! The solution was to remove -nochromium from the launch options.
