### ISSUE TITLE
Is there a way to restore HTML w/o running the installer?

### ISSUE THREAD

**Issue by gmod64bit** [solsticegamestudios/GModCEFCodecFix#56]
I am running Gmod 64 bit through proton for development purposes, but HTML doesn't work. Unfortunately I can't get the exetuble to run through protontricks or wine.

So, is there a way to fix the broken HTML menu/HTML chats, MOTD's, etc, without fully installing the executable provided in the release? Thank you!

P.S: I'm aware of the no-html menu on github, but that only cures the menu (but excludes the server list, the legacy list is Puke)

**Comment by AkikoKumagara** [comment]
GModCEFCodecFix doesn't support Proton (yet!), but hopefully in the future! Our tests thus far have not been successful under that kind of configuration. We typically recommend running the native build of Garry's Mod instead.
