### ISSUE TITLE
No GMod Menu Showing up + Crash when loading up a map through console

### ISSUE THREAD

**Issue by huellbabineaux** [solsticegamestudios/GModCEFCodecFix#57]
Hi, I followed the guide for this, and this is end product
![image](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/127367087/e3842e5a-b19f-4c87-afaf-6cba7e6bc2c8)
When I launch the game, I can see the GMod loading up for a second, and then its just a blue background, when I type in console "map (a map)" it minimizes it, and says "Engine Error: 'gamemode' library is not a table, make sure addon is not overwriting it"

I have my settings like this:
x86 -64 - Chromium + 64-bit binaries
My computer is a MacBook Air M1 2020
Is there a solution to this?

**Comment by WinterPhoenix** [comment]
This sounds like two separate issues. Does the main menu load? Can you see options on the left side for “Start Game” etc?

**Comment by WinterPhoenix** [comment]
Wait, I just noticed you have gmod-lua-menu. Uninstall that, remove `-nochromium` from your launch options, then run the tool again.

**Comment by huellbabineaux** [comment]
> Wait, I just noticed you have gmod-lua-menu. Uninstall that, remove `-nochromium` from your launch options, then run the tool again.

Got you, I uninstalled GMod completely and I will start from scratch.

**Comment by huellbabineaux** [comment]
It worked, I wouldn't suppose there's a way to change the resolution or why the game just zooms in, but I can see the menu fine, thank you.

**Comment by AkikoKumagara** [comment]
> 

Set the resolution manually using `-w` and `-h` in launch options.
Example for 1080p display:
`-w 1920 -h 1080`

Sometimes GMod is funny about setting resolution, especially on non-Windows operating systems, but forcing it as a launch option should help.

**Comment by huellbabineaux** [comment]
awesome, thank you so much for your help
