### ISSUE TITLE
Why is Chromium, upon starting patched GMOD attempting to access my KDE Password Vault??

### ISSUE THREAD

**Issue by 18iteration** [solsticegamestudios/GModCEFCodecFix#58]
![Screenshot_20230601_023743](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/45468984/65f94394-e995-4188-b4de-34008257274c)
As you can see in the screenshot upon starting GMOD patched with this codec, Chromium (patched chromium) attempts to access my KDE password vault, which I permanently denied of course.

What is the explanation here? GMOD / chromium never asked for access to my password vault! Only once I ran the patch from a terminal and started the game did this attempted access occur.

**Comment by WinterPhoenix** [comment]
I guarantee it's not actually, unless you have a build infected with malware, or got from somewhere other than this repo's [Releases page](https://github.com/solsticegamestudios/GModCEFCodecFix/releases).

It's probably querying for sudo or something so it can attempt to automatically set up Locale or do CefSandbox stuff.

**Comment by 18iteration** [comment]
> I guarantee it's not actually, unless you have a build infected with malware, or got it from somewhere other than this repo's [Releases page](https://github.com/solsticegamestudios/GModCEFCodecFix/releases).
> 
> It's probably querying for sudo or something so it can attempt to automatically set up Locale or do CefSandbox stuff.

I downloaded the build from this repo.

**Comment by WinterPhoenix** [comment]
Yeah, I don’t know why it seems to be triggering that. Again, pretty sure it’s actually just sudo and for some reason it’s being presented that way.
