### ISSUE TITLE
Chat feature not working on latest update

### ISSUE THREAD

**Issue by anthonykour** [solsticegamestudios/GModCEFCodecFix#59]
Using most recent version of Gmod Chromium, and CEF Patch, on Ubuntu 23.04 with Nvidia Drivers 535, I'm unable to use the chat feature on Swamp Cinema. Everything else seems to be working. Oh I did have to use the SDL file from CSGO to fix the dual screen detection issue, but that's working fine now, after I copied over that file. The chat is broken though.

**Comment by WinterPhoenix** [comment]
There was an issue with Swamp Cinema's Chatbox that made it unstable with the latest CEF update. It should be fixed now.
