### ISSUE TITLE
Installer does not detect Garry's Mod when installation path is under the username folder instead of the "common" folder.

### ISSUE THREAD

**Issue by Wiiplay123** [solsticegamestudios/GModCEFCodecFix#6]
I first bought Garry's Mod in 2010 and have had it installed since then, never reinstalling. Back then, Steam games would install under steamapps/wiiplay123 instead of steamapps/common. I was able to make a symlink using mklink to make it install correctly but it would be nice for those of us who have had Garry's Mod since before the switch to the common folder to not have to do that.

**Comment by WinterPhoenix** [comment]
What is the absolute path of your Garry's Mod install?

**Comment by Wiiplay123** [comment]
C:\Program Files (x86)\Steam\steamapps\wiiplay123\garrysmod

**Comment by WinterPhoenix** [comment]
Should be fixed in https://github.com/solsticegamestudios/GModCEFCodecFix/commit/986d8bb0ee17fdc4462fbf93915bfac79c064fd0 , thanks for the report!
