### ISSUE TITLE
Stuck At ''Lua Started!'' on Linux

### ISSUE THREAD

**Issue by githubmanlinus** [solsticegamestudios/GModCEFCodecFix#61]
So i Used This Tool on Linux and it Kinda Worked but every Time i load into a Map it gets stuck at Lua Started!
Im using Ubuntu 23.10 And My Specs are
 CPU: 6-core Intel Core i5-10400 (-MT MCP-)
Kernel: 6.3.0-7-generic x86_64
 Mem: 5798.3/31993.2 MiB (18.1%)
Storage: 2.73 TiB (28.3% used)
 Procs: 381
 Shell: Bash 
inxi: 3.3.27
GPU: RTX 2080 Ti

**Comment by WinterPhoenix** [comment]
Could you verify game integrity, run the tool again, and let me know if you're still encountering this issue? Some stuff has shifted around in the last couple days due to the [recent GMod update](https://store.steampowered.com/news/app/4000/view/3672171270309976082?l=english).

**Comment by othello777** [comment]
This happens for me when using Toybox Classics or Toybox Reworked

**Comment by WinterPhoenix** [comment]
Do those addons use CEF/web panels in some way?

**Comment by githubmanlinus** [comment]
yea anyway it worked now
