### ISSUE TITLE
Bitmining???

### ISSUE THREAD

**Issue by UberKamek85** [solsticegamestudios/GModCEFCodecFix#62]
Not to accuse you people of anything, but I've heard somewhere that this codec jacks peoples' computers and uses them for bitmining?? Is this true? I really hope not, and in fact I'm kind of in doubt.

**Comment by WinterPhoenix** [comment]
lol not a chance. read the code, it’s open source

**Comment by Ijustplaymc** [comment]
lmao no 

read the code ya dunce
