### ISSUE TITLE
Missing icons and textures

### ISSUE THREAD

**Issue by Hoplite1111** [solsticegamestudios/GModCEFCodecFix#65]
All of the weapon icons and things like the crosshair are replaced with letters.
<img width="1440" alt="Screenshot 2023-07-24 at 6 18 55 PM" src="https://github.com/solsticegamestudios/GModCEFCodecFix/assets/136226630/29acec17-3822-498f-874f-158b4b6540da">

**Comment by WinterPhoenix** [comment]
This isn't a GModCEFCodecFix issue, this is a GMod issue. Try doing Steam > Garry's Mod > Properties > Installed Files > Verify integrity of game files.

If that doesn't work, ask for help in the official Garry's Mod Discord: https://discord.gg/gmod
