### ISSUE TITLE
Error during the GModCEFCodecFix-macOS execution

### ISSUE THREAD

**Issue by paraboom** [solsticegamestudios/GModCEFCodecFix#66]
Hello, guys! I've tried to apply your tool, it downloaded and applied patches for the most of the files, but I've got the error in the middle of the process:

```
Fixing Files...
	Patching: GarrysMod_Signed.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libEGL.dylib...
	Exception (Fixed): [Errno 1] Operation not permitted: '/Users/paraboom/Library/Application Support/Steam/steamapps/common/GarrysMod/GarrysMod_Signed.app/Contents/Frameworks/Chromium Embedded Framework.framework/Libraries/libEGL.dylib'
```

<img width="1226" alt="image" src="https://github.com/solsticegamestudios/GModCEFCodecFix/assets/385424/aa0b0a0f-6cd6-4f3f-a78c-fee116c91bcd">

**Comment by AkikoKumagara** [comment]
Hello! We had someone experience a very similar issue yesterday and resolved it by simply doing the following.

1. Reboot the computer
2. Start Steam
3. Ensure Garry's Mod is not running in any capacity
4. Run GModCEFCodecFix again.

Hope this helps. Let us know if there's still a problem.

**Comment by paraboom** [comment]
@AkikoKumagara thanks for that suggestion, but it's still not working properly. I've downloaded the fresh version, which was released yesterday, checked the integrity, stopped GMode and tried the script again. The error more or less the same:
<img width="1225" alt="Screenshot 2023-07-30 at 12 53 16" src="https://github.com/solsticegamestudios/GModCEFCodecFix/assets/385424/ad83aa51-41c3-48dc-8c62-32c5dd0c2430">

**Comment by AkikoKumagara** [comment]
> @AkikoKumagara thanks for that suggestion, but it's still not working properly. I've downloaded the fresh version, which was released yesterday, checked the integrity, stopped GMode and tried the script again. The error more or less the same: <img alt="Screenshot 2023-07-30 at 12 53 16" width="1225" src="https://user-images.githubusercontent.com/385424/257046717-ad83aa51-41c3-48dc-8c62-32c5dd0c2430.png">

Assuming GMod isn't running or trying to update/pending update: Something else on your system is accessing those files and preventing them from being patched as a result. What could be doing that could be many things, unfortunately...
