### ISSUE TITLE
I keep getting Error: One or More Files failed to match the Original Checksum! after a recent GMOD update.

### ISSUE THREAD

**Issue by AmbassadorLaZer** [solsticegamestudios/GModCEFCodecFix#68]
![WindowsTerminal_cjIla3RAGx](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/54087473/34431bf3-fa7a-4705-9590-3eaacca406d5)

I've verified the game at least two times since updating the game and its successfully verified all the files both times. I'm guessing that the update might've removed one of the files that the program uses for the checksum. I don't know though, but I keep on getting the error. Hopefully this could be fixed and resolved soon! :)

Thanks!

**Comment by WinterPhoenix** [comment]
Try again in about an hour

**Comment by AmbassadorLaZer** [comment]
Sure thing!

**Comment by WinterPhoenix** [comment]
It should work now, give it a shot

**Comment by AmbassadorLaZer** [comment]
It worked! Thanks for fixing it!
