### ISSUE TITLE
Bug with the most recent version.

### ISSUE THREAD

**Issue by EmeraldWizardX** [solsticegamestudios/GModCEFCodecFix#7]
#I am trying to install codecs for Garry's mod, but it keeps saying "Error: One or More Files Failed to Match the Original Checksum! Please Verify Garry's Mod Integrity and Try Again!" even though I have verified gmod's integrity. and I don't know what to do.

**Comment by WinterPhoenix** [comment]
Fixed in https://github.com/solsticegamestudios/GModCEFCodecFix/commit/5439c11c108fbebb74851b96da9571e962a024c5
