### ISSUE TITLE
It doesn't work on NixOS

### ISSUE THREAD

**Issue by dnkmmr69420** [solsticegamestudios/GModCEFCodecFix#72]
The current workaround is to run it in a distrobox container like arch, fedora, ubuntu and nixos uses `/run/current-system/sw` instead of `/usr/bin` and nixos uses the nix store too.

error

```
bash: /home/username/Downloads/GModCEFCodecFix-Linux: cannot execute: required file not found
```

**Comment by WinterPhoenix** [comment]
We don't officially support or test NixOS. Consider using SteamOS (Steam Deck), Arch Linux, or Ubuntu. You're on your own otherwise
