### ISSUE TITLE
issue with macos

### ISSUE THREAD

**Issue by scouttttt** [solsticegamestudios/GModCEFCodecFix#73]
whenever using the cef codec fix it lists this error in specific

"GarrysMod_Signed.app/Contents/Frameworks/gmod Helper.app/Contents/MacOS/gmod Helper: Does Not Match Original!"

this also happens with multiple other files. i'm guessing this is due to a new update?

thanks in advance

**Comment by scouttttt** [comment]
<img width="565" alt="Screenshot 2023-08-08 at 10 29 35 AM" src="https://github.com/solsticegamestudios/GModCEFCodecFix/assets/141754557/3a84feff-8a6d-46b5-8d9e-80f57699355e">

**Comment by AkikoKumagara** [comment]
There was an update. You're right. Try again now as our automated manifest regeneration has run again.
