### ISSUE TITLE
AUR version fails as it tries to write to /usr/bin/

### ISSUE THREAD

**Issue by crazybrain23** [solsticegamestudios/GModCEFCodecFix#75]
Program fails as it tries to access write files to /usr/bin/
```
Traceback (most recent call last):
  File "GModCEFCodecFix.py", line 496, in <module>
FileExistsError: [Errno 17] File exists: '/usr/bin/GModCEFCodecFixFiles'
[21246] Failed to execute script 'GModCEFCodecFix' due to unhandled exception!
```
I think it would be better to use XDG_CACHE_HOME or something instead.

It works fine when downloaded manually and ran from the Downloads directory.

**Comment by AkikoKumagara** [comment]
Good idea. I'll make the changes needed to accommodate this.

**Comment by AkikoKumagara** [comment]
I put in a PR (#76) which addresses this issue. I really appreciate you bringing this to our attention as I didn't realize this could happen, it was never a problem for me.

**Comment by WinterPhoenix** [comment]
This should be fixed in code and the next release will include it

**Comment by AkikoKumagara** [comment]
The fix for this is now live in the latest release 20230929.
