### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by itsprop** [solsticegamestudios/GModCEFCodecFix#77]
I've installed the codec fix for windows, It installed with no issues but when I get in game and try to view a video that requires this codec fix it just shows a black screen is there any fix for this?

**Comment by WinterPhoenix** [comment]
Need a lot more context for this. What addon/server are you using to watch the video? Did you run the CEFCodecFix tool and did it say it applied successfully?

**Comment by itsprop** [comment]
It fixed itself as of today.
