### ISSUE TITLE
garrysmod/lua/menu/mainmenu.lua: Does Not Match Original [Linux x86_64]

### ISSUE THREAD

**Issue by sefaru** [solsticegamestudios/GModCEFCodecFix#80]
Happens when trying to patch x64 version of Garry's mod. Completely reinstalled the game (with complete deletion of the Garry's mod directory). 

File in txt format:
[mainmenu.txt](https://github.com/solsticegamestudios/GModCEFCodecFix/files/12717673/mainmenu.txt)

**Comment by AkikoKumagara** [comment]
This is normal (for some time) after GMod is updated, which it was today. Our automated update check runs every six hours and has since run. This should be fixed.
