### ISSUE TITLE
Dosen't detect Gmod On Flatpak Steam (Linux)

### ISSUE THREAD

**Issue by githubmanlinus** [solsticegamestudios/GModCEFCodecFix#81]
So i recently switched to Flatpak Steam because some games didn't work on normal Steam.
I wanted to use this tool on gmod again but it wouldn't detect Gmod
Please Help Me Fix This Problem
Thank You :)

**Comment by githubmanlinus** [comment]
![):](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/110555110/9ab58ed8-2452-4c42-b74c-0cda4af502ae)

**Comment by AkikoKumagara** [comment]
We already have an issue open for this sort of thing. We plan to support Flatpak more fully in the next update, but for now it probably won't work.

https://github.com/solsticegamestudios/GModCEFCodecFix/issues/64

Try not to create duplicate issues in the future, and instead leave comments on existing ones if they're still open and about the same subject.

It would be helpful if you could send us what your correct GMod/Steam filepaths are (while using Flatpak) so we can make sure the executable is checking there for the game and appmanifest files.

**Comment by githubmanlinus** [comment]
Ok So i didnt see the other post about this. Anyway here is my Steam Filepath (with the appmanifests) /home/user here/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps and here is the one with gmod /home/linus/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/GarrysMod
And also when are you planning to release the next update?

**Comment by AkikoKumagara** [comment]
> And also when are you planning to release the next update?

Probably reasonably soon. We have to build updated CEF for every platform and test, as well as get Flatpak support implemented and tested, so it may take some time depending on developer availability. The code for this project is open source and anyone can contribute, but a lot of the work usually falls onto @WinterPhoenix for things like this.

**Comment by AkikoKumagara** [comment]
Should be working fully as of the [latest release](https://github.com/solsticegamestudios/GModCEFCodecFix/releases)
