### ISSUE TITLE
Houston, we have a problem. (Matching the original checksum error)

### ISSUE THREAD

**Issue by Legosi13** [solsticegamestudios/GModCEFCodecFix#82]
<img width="570" alt="Screenshot 2023-09-27 at 11 01 12" src="https://github.com/solsticegamestudios/GModCEFCodecFix/assets/67709387/69c9dcc4-3ccd-42a7-9b58-66c607d40519">
Not sure if this is a current issue among users of this lifesaver, but I'm having issues with making it work. Used to work but haven't done anything in particular to make such an anomaly happen. I've already verified the game files, even reinstalled and hopped from different branches (I primarily and can only use the x86_x64 branch ofc), but to no avail. Using MacOS 12.6.3 Monterey. What can I do? Any and all help is greatly appreciated~ <3

**Comment by AkikoKumagara** [comment]
Update check is running now. Try in 35 minutes and it should be working.

**Comment by Legosi13** [comment]
Thanks again, I look forward to using it again! ^w^
