### ISSUE TITLE
Dosen't Detect if GMod is on Proton or not. 

### ISSUE THREAD

**Issue by githubmanlinus** [solsticegamestudios/GModCEFCodecFix#84]
so basically i wanted to use this on proton but it said it didn't   "using proton no"   even though i set gmod to proton experimental in settings - compatibility - Force The Use Of A Specific Compatibility Tool - Proton Experimental and basically every other proton version yes i tried all of them (accept for the really old ones) 

![Screenshot from 2023-10-01 09-38-44](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/110555110/85598584-bd76-43ed-a5a7-cd7ae5cbc7df)

**Comment by WinterPhoenix** [comment]
Given that you closed this, I imagine you just weren't waiting for Steam to finish the change?
