### ISSUE TITLE
Menu not showing on Linux + No support for unprivileged usernamespaces. Loading Stub instead of Chromium... (Linux Ubuntu)

### ISSUE THREAD

**Issue by githubmanlinus** [solsticegamestudios/GModCEFCodecFix#85]
So i wanted to play on linux and like it used to work perfectly fine with the menu and everything i coould play but now when i launch garrys mod with gmod cef codec fix it dosent show the menu and says in the console: "No support for unprivileged usernamespaces. Loading Stub instead of Chromium..." Here is a Picture Of the Problem. 

![Screenshot from 2023-10-03 09-06-21](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/110555110/d2fb04f4-b000-4097-ab78-f5a5add5af65)

Also the background is from a tardis backgrounds mod

**Comment by AkikoKumagara** [comment]
If you're using the Flatpak version of Steam, this behavior is expected (see https://github.com/solsticegamestudios/GModCEFCodecFix/pull/83).

If you're not using the Flatpak version of Steam, then you need to enable unprivileged user namespaces on your kernel.

Most, but not all, distros come with unprivileged user namespaces already enabled on the kernel level. You should be aware of what unprivileged user namespaces are before enabling them as this can be a security risk for the user, but this is required for Chromium Embedded Framework to work in GMod with sandboxing.

The process can be done and made persistent in two steps as follows:

```
sysctl -w kernel.unprivileged_userns_clone=1
``` 

```
echo "kernel.unprivileged_userns_clone=1" >> /etc/sysctl.conf
```
