### ISSUE TITLE
CEFCodecFix is a virus according to Windows Security (Trojan Win32/Wacatac.D6!ml)

### ISSUE THREAD

**Issue by PentiumMMX166** [solsticegamestudios/GModCEFCodecFix#9]
Windows Security Anti Virus has quaranteed this file and thinks it's a really bad trojan virus. Is it a false positive, or is it really dangerous?

**Comment by WinterPhoenix** [comment]
Duplicate of #8

**Comment by GeneralFriendly** [comment]
Confirming that the new build is no longer flagged.
