### ISSUE TITLE
Problem with /bin/linux64/libcef.so

### ISSUE THREAD

**Issue by thegoldster289** [solsticegamestudios/GModCEFCodecFix#90]
While running the program (first time installing, haven't got to open gmod with it yet), the program downloads everything fine except for libcef.so. It will say "Patching: bin/linux64/libcef.so...", freeze my computer for anywhere from 5 seconds to a minute, then crash and exit. Are there any fixes to this?

Edit: Forgot to mention, I'm using Debian 12 currently with x86_64 Intel(R) Celeron(R) N4020 CPU @ 1.10GHz and 4 gb RAM (just in case that's needed).

**Comment by WinterPhoenix** [comment]
You're probably running out of RAM lol Watch System Monitor or something while running the tool to find out for sure

I dunno if we'll be able to do anything about it, since 4GB is NOT a lot nowadays, but I'll take a look

**Comment by thegoldster289** [comment]
Went to check system monitor and it suddenly started working lol. Weird cause I tried it multiple times on multiple days. Thanks!
