### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by CloakerMacguy** [solsticegamestudios/GModCEFCodecFix#92]
I did everything shown in this video https://www.youtube.com/watch?v=VL8sIokUulU&ab_channel=AkikoKumagara.

It did nothing, NOTHING I TELL YOU. (My current mac version is Mac Monterey Version 12.6) How can I get this to work because I really don't want to wake up with the message "UH OH, YOU'VE WASTED 5 BUCKS ON GMOD BOZO, MAYBE GET A WINDOWS DUMBASS"

**Comment by WinterPhoenix** [comment]
macOS Support is very hit or miss. See https://github.com/solsticegamestudios/GModCEFCodecFix/issues/87

**Comment by CloakerMacguy** [comment]
Nevermind, it worked after I tried it a few more times, thanks goober!
