### ISSUE TITLE
Doesn't do anything on Ubuntu 22.04 Jammy.

### ISSUE THREAD

**Issue by tteletubby** [solsticegamestudios/GModCEFCodecFix#93]
**I've done the tutorial from here
https://www.youtube.com/watch?v=Nsilmi0YiWw**

And yes, I've set up the x86-64x chromium branch and did the setup as in the video, just doesn't open at all, what now?

**Comment by AkikoKumagara** [comment]
What isn't opening? The executable or Garry's Mod?

**Comment by tteletubby** [comment]
Garry's mod isn't opening at all.

**Comment by AkikoKumagara** [comment]
> Garry's mod isn't opening at all.

Thanks. So the GModCEFCodecFix-Linux executable runs and completes successfully?

**Comment by tteletubby** [comment]
Yes, but gmod doesn't open at all. It says "opened" but the window never opens and just shuts down.

**Comment by AkikoKumagara** [comment]
> Yes, but gmod doesn't open at all. It says "opened" but the window never opens and just shuts down.

Does the same thing happen if you try running GMod through Steam itself?

**Comment by tteletubby** [comment]
Yes.

**Comment by AkikoKumagara** [comment]
Is your Steam installed via Flatpak by chance?

**Comment by tteletubby** [comment]
i'm not sure actually, I did it by going to terminal and executing the following command
**sudo apt-get install steam**

**Comment by AkikoKumagara** [comment]
> i'm not sure actually, I did it by going to terminal and executing the following command **sudo apt-get install steam**

Hmm, nope, that's correct.

**Comment by tteletubby** [comment]
I'm not sure what to do. I did all steps as in the video and checked my **beta** settings but it just doesn't work.

**Comment by AkikoKumagara** [comment]
Try validating game files and run the game without running the executable first. Let me know if it behaves the same or launches successfully.

**Comment by tteletubby** [comment]
yeah, the menu opened and downloaded my addons but only the wallpaper is seen on gmod menu screen and no way to choose anything. 
Picture of my gmod menu after the addons downloaded

![Uploading image.png…]()

**Comment by AkikoKumagara** [comment]
Thanks for confirming that. Now can you try running the executable once again? Make sure Steam is running but GMod is closed when you.

**Comment by tteletubby** [comment]
https://imgur.com/a/Bvkla8j

**Comment by tteletubby** [comment]
i've tried and it still just shows the wallpaper

**Comment by AkikoKumagara** [comment]
@WinterPhoenix please help.

**Comment by tteletubby** [comment]
Bigger problem now.
After restarting my system due to other reasons, I tried to open gmod and it just opens for 0.5 seconds and closes instantly, opening the GMODCEFCODECFIX again gives me this error

**Found Garry's Mod Manifest:
/home/transmitter/.local/share/Steam/steamapps/appmanifest_4000.acf

Garry's Mod Branch:
x86-64

Garry's Mod State:
4

Getting Steam Config...
Getting Steam AppInfo for GMod...
	Platform: linux
	Is Using Proton: No
	/home/transmitter/.local/share/Steam/steamapps/common/GarrysMod/hl2.sh
		[Errno 2] No such file or directory
Error: Could not detect GMod EXE Launch Options!

If you need help, follow the Guide first:
- https://www.solsticegamestudios.com/forums/threads/60/

If that doesn't work, contact us:
- Discord: https://www.solsticegamestudios.com/chat.html
- Email: contact@solsticegamestudios.com
**

**Comment by WinterPhoenix** [comment]
No such file or directory with hl2.sh means Proton broke. You have two options:

1. Use Native: Toggle Proton off, then on, then off again
2. Use Proton: Toggle Proton off, then on

After doing one of those, verify game integrity, then run GModCEFCodecFix-Linux again, and let us which option you chose and how things look.

**Comment by tteletubby** [comment]
Okay, I will try.

**Comment by tteletubby** [comment]
I tried both techniques that you provided and none of them do the trick.

**Comment by WinterPhoenix** [comment]
Didn't do the trick how? What do you see?

**Comment by tteletubby** [comment]
I've done the stuff that you asked me to do above, same stuff happen, the game loads addons as normal but all I see is the main menu wallpaper changing and no buttons to choose anything. That's all.

**Comment by AkikoKumagara** [comment]
> I've done the stuff that you asked me to do above, same stuff happen, the game loads addons as normal but all I see is the main menu wallpaper changing and no buttons to choose anything. That's all.

What do you have in GMod launch options currently? If you have `-nochromium`, please remove it.

**Comment by tteletubby** [comment]
I have nothing in the launch options.

**Comment by tteletubby** [comment]
I've tried in Debian 12 the same instructions, here is what I got.

https://youtu.be/BjAw5NSX9XE

**Comment by WinterPhoenix** [comment]
Try again with Steam Linux Runtime

**Comment by tteletubby** [comment]
![image](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/154614611/fbe85922-8416-49e2-97ff-841921db7995)
Still nothing.

**Comment by WinterPhoenix** [comment]
Delete chromium.log and try launching GMod again with Steam Linux Runtime set in Compatibility. Then take a look at in-game console and chromium.log (if present) for clues. I'm gonna bet it's a missing library

**Comment by tteletubby** [comment]
No support for unprivileged usernamespaces. Loading Stub instead of Chromium...
x86-64: gmod_mcore_test=1
Parent cvar in server.dll not allowed (p2p_enabled)
Parent cvar in server.dll not allowed (props_break_max_pieces)
Did not detect any valid joysticks.
Unknown command "commentary_firstrun"
cc_lang: invalid language
Using joystick 'Xbox360 controller' configuration
JOY_AXIS_X:  mapped to Side (absolute)
JOY_AXIS_Y:  mapped to Forward (absolute)
JOY_AXIS_Z:  unmapped
JOY_AXIS_R:  mapped to Look (absolute)
JOY_AXIS_U:  mapped to Turn (absolute)
JOY_AXIS_V:  unmapped
Advanced Joystick settings initialized
Not playing a local game.
'M9K Specialties' is missing Addon, ServerContent, Dupe, Demo or Save tag!
m_face->glyph->bitmap.width is 0 for ch:32 DejaVu Sans
Addons have changes - remounting

**Comment by AkikoKumagara** [comment]
Are you using Flatpak Steam? If so, that configuration isn't supported and explains everything.
If not, you'll need to check if unprivileged user namespaces are enabled in your kernel.

**Comment by tteletubby** [comment]
Yes, I'm using Debian 12 as of recent times, so yes its from flatpak. I'll check if unprivileged user namespaces are enabled in my kernel.

I will update shortly.

**Comment by tteletubby** [comment]
teletubby@debian:~$ sudo sysctl kernel.unprivileged_userns_clone

kernel.unprivileged_userns_clone = 1


This means it's enabled, what next?

**Comment by AkikoKumagara** [comment]
> Yes, I'm using Debian 12 as of recent times, so yes its from flatpak. I'll check if unprivileged user namespaces are enabled in my kernel.
> 
> I will update shortly.

Flatpak Steam is unsupported because we can't use CEF inside of bubblewrap currently. You'll need to install Steam via the .deb release.

**Comment by tteletubby** [comment]
Ah yes, I haven't thought of using steam's deb release on their official site, I was setting up the .deb steam for about an hour so i'll update in about an hour to see what happens

**Comment by tteletubby** [comment]
Hi, it worked thanks for helping!

**Comment by WinterPhoenix** [comment]
@LethalManBoob 
> busted on arch

https://github.com/solsticegamestudios/GModCEFCodecFix/issues?q=arch

Or if you can't find the issue you're having, make an issue
