### ISSUE TITLE
GMod uses Integrated GPU instead of the Dedicated GPU after installing patch

### ISSUE THREAD

**Issue by gingusScringus** [solsticegamestudios/GModCEFCodecFix#95]
I figured I'd use this patch because i wanted to try playing GMod on my (K)ubuntu 22.04 install. However it kept crashing when I load the map. Then I installed this patch and it worked!

However, I noticed that my fps wasn't as high as how I usually play on my Windows install. I thought that was because of games on Linux aren't really optimized the most than on Windows. Later on, I hopped onto my Windows install to play normally and installed the CEF patch, hoping to get some FPS boost and a bunch of fixes. But turns out, I got the opposite.

I got a sub-60 FPS gameplay even with gmod_mcore_test, at first I didn't know how this happened. But when i look at my Task Manager, it turns out that for some reason the game is running on the iGPU instead of my dGPU. Out of curiosity, I tried verifying my game files and it's running on my dGPU now. I also tried forcing my game to run on my dGPU by going to the graphics settings on the Windows Settings and forcing it to use the High-performance option

There's also [this closed issue](https://github.com/solsticegamestudios/GModCEFCodecFix/issues/25) that has the same problem as mine.

I have a Windows 10 22H2 with a Kubuntu 22.04 on a separate partition, 16GB RAM, Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz   2.59 GHz, and an NVIDIA GeForce RTX 2070 with Max-Q Design GPU (8GB VRAM)

Also, while I do have a lot of addons. I don't think it's the problem with the addons.

**Comment by WinterPhoenix** [comment]
This isn't a problem with CEFCodecFix, this is a problem with your graphics control panel settings. Tell your GPU control panel to run GMod with the dGPU. CEFCodecFix patches the executable, so it may see it as "different" from before.

As far as Linux goes, there's an enormous amount of difference between running GMod on Linux compared to Windows. It might be better, it might be worse, it might be about the same, entirely depending on your hardware, drivers, and distro.

Some people have a large performance boost running GMod in Proton on Linux, even, but that comes with its own set of issues.

**Comment by gingusScringus** [comment]
> This isn't a problem with CEFCodecFix, this is a problem with your graphics control panel settings. Tell your GPU control panel to run GMod with the dGPU. CEFCodecFix patches the executable, so it may see it as "different" from before.
> 
> As far as Linux goes, there's an enormous amount of difference between running GMod on Linux compared to Windows. It might be better, it might be worse, it might be about the same, entirely depending on your hardware, drivers, and distro.
> 
> Some people have a large performance boost running GMod in Proton on Linux, even, but that comes with its own set of issues.

It worked! Apparently, Windows Settings is just crap and didn't do it's job correctly. I didn't look into the NVIDIA Control Panel settings because the program itself said that the graphics are now managed by the Windows Settings. Now it's running on my dGPU again.

Figured. Hopefully Linux support would be better on games as Steam Deck and it's SteamOS Linux distro grows up.

Anyway, thanks!
