### ISSUE TITLE
CEFCodecFix causes reloading problems

### ISSUE THREAD

**Issue by obscurefreeman** [solsticegamestudios/GModCEFCodecFix#98]
After downloading the CEFCodecFix, I found that running the "reload" command caused the game to crash. How can I fix this issue?
![20240120115442_1](https://github.com/solsticegamestudios/GModCEFCodecFix/assets/119153032/260a2e6d-c78f-4555-b520-ee0aad1697d1)

**Comment by WinterPhoenix** [comment]
In what context are you running `reload`?

**Comment by obscurefreeman** [comment]
It's solved. It's an addon conflict, not a CEF‘s fault.
